name: CI

on:
  push:
    branches:
      - main
      - 'releases/**'
  workflow_call:
  workflow_dispatch:

jobs:
  check_package:
    name: Check ${{ matrix.package-name }}
    strategy:
      matrix:
        include:
          - package-name: ni.grpcdevice.v1.proto
            proto-basepath: ../../proto
            proto-subpath: ni/grpcdevice/v1
            proto-include-path: ../../proto
            output-format: subpackage
          - package-name: ni.measurementlink.discovery.v1.proto
            proto-basepath: ../../third_party/ni-apis
            proto-subpath: ni/measurementlink/discovery/v1
            proto-include-path: ../../third_party/ni-apis
            output-format: subpackage
          - package-name: ni.measurementlink.measurement.v1.proto
            proto-basepath: ../../third_party/ni-apis
            proto-subpath: ni/measurementlink/measurement/v1
            proto-include-path: ../../third_party/ni-apis
            output-format: subpackage
          - package-name: ni.measurementlink.measurement.v2.proto
            proto-basepath: ../../third_party/ni-apis
            proto-subpath: ni/measurementlink/measurement/v2
            proto-include-path: ../../third_party/ni-apis
            output-format: subpackage
          - package-name: ni.measurementlink.proto
            proto-basepath: ../../third_party/ni-apis
            proto-subpath: ni/measurementlink
            proto-include-path: ../../third_party/ni-apis
            output-format: subpackage
          - package-name: ni.measurementlink.sessionmanagement.v1.proto
            proto-basepath: ../../third_party/ni-apis
            proto-subpath: ni/measurementlink/sessionmanagement/v1
            proto-include-path: ../../third_party/ni-apis/ni/grpcdevice/v1
            output-format: subpackage
          - package-name: ni.panels.v1.proto
            proto-basepath: ../../third_party/ni-apis
            proto-subpath: ni/panels/v1
            proto-include-path: ../../third_party/ni-apis
            output-format: submodule
          - package-name: ni.protobuf.types
            proto-basepath: ../../third_party/ni-apis
            proto-subpath: ni/protobuf/types
            proto-include-path: ../../third_party/ni-apis
            output-format: submodule
    uses: ./.github/workflows/check_package.yml
    with:
      package-name: ${{ matrix.package-name }}
      proto-basepath: ${{ matrix.proto-basepath }}
      proto-subpath: ${{ matrix.proto-subpath }}
      proto-include-path: ${{ matrix.proto-include-path }}
      output-format: ${{ matrix.output-format }}
  check_analyzers_grpc_gen:
    name: Check analyzers for grpc_generator
    uses: ./.github/workflows/check_analyzers.yml
    with:
      package-name: grpc_generator
      package-base-path: tools
  run_unit_tests:
    name: Run unit tests
    uses: ./.github/workflows/run_unit_tests.yml
    needs: [check_package, check_analyzers_grpc_gen]
  report_test_results:
    name: Report test results
    uses: ./.github/workflows/report_test_results.yml
    needs: [run_unit_tests]
    if: always()
    permissions:
      contents: read
      checks: write
      pull-requests: write